services:
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    container_name: kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - kafka-network
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --describe
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5

  influxdb:
    image: influxdb:latest
    hostname: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=sic
      - DOCKER_INFLUXDB_INIT_BUCKET=tp2
      - DOCKER_INFLUXDB_INIT_RETENTION=7d  # Retención de datos (7 días)
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=LRk4Qb4QtnFqdn83kYDG-1EXsNRkhFGrdZqJQhfy2IOTN7IIyVhWdwEu8PeKlvhXDHomucMZVOpE7tAPLSx0xQ==
    networks:
      - tick-network
    volumes:
      - influxdb-conf:/etc/influxdb2 
      - influxdb-data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 20s
      timeout: 30s
      retries: 5
  
  telegraf:
    image: telegraf:latest
    hostname: telegraf
    container_name: telegraf
    depends_on:
      influxdb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
      - tick-network
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
      - INFLUXDB_URL=http://influxdb:8086
      - KAFKA_BROKER=kafka:9092
    healthcheck:
      test: ["CMD", "telegraf", "--test"]
      timeout: 10s
      retries: 1
      start_period: 10s

  humidity-sensor:
    image: humidity-python:1.0
    hostname: sHumidity
    container_name: humidity-sensor
    build: ./HumProducer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
    environment:
      - MEAN_HUMIDITY=60
      - STD_HUMIDITY=15
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=sh-humidity

  cooling-sensor:
    image: cooling-python:1.0
    hostname: sCooling
    container_name: cooling-sensor
    build: ./CooProducer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
    environment:
      - MEAN_COOLING=10
      - STD_COOLING=5
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=sh-cooling

  temp1-sensor:
    image: temp1-python:1.0
    hostname: sTemperature
    container_name: temp1-sensor
    build: ./Temp1Producer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
    environment:
      - MEAN_TEMPERATURE=15
      - STD_TEMPERATURE=5
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=sh-temperature
  
  temp2-sensor:
    image: temp2-python:1.0
    hostname: sTemperature
    container_name: temp2-sensor
    build: ./Temp2Producer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
    environment:
      - MEAN_TEMPERATURE=15
      - STD_TEMPERATURE=5
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=sh-temperature
  
  temp3-sensor:
    image: temp3-python:1.0
    hostname: sTemperature
    container_name: temp3-sensor
    build: ./Temp3Producer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
    environment:
      - MEAN_TEMPERATURE=15
      - STD_TEMPERATURE=5
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=sh-temperature

  power-sensor:
    image: power-python:1.0
    hostname: sPower
    container_name: power-sensor
    build: ./PowProducer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-network
    environment:
      - MEAN_POWER=60
      - STD_POWER=15
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=sh-power

networks:
  kafka-network:
    name: kafka-network
    external: false
  tick-network:
    name: tick-network
    external: false

volumes:
  telegraf:
    driver: local
  influxdb-conf:
    driver: local
  influxdb-data:
    driver: local
## hostname for the influxdb: 0e03e1f4b35ba000